In [1]:
from pathlib import Path
results_path = Path('output/results/CW_1x5_Dynamic_Complete/20251212-182251')
results_path

WindowsPath('output/results/CW_1x5_Dynamic_Complete/20251212-182251')

In [2]:
from src.reporting import load_results_from_path, parse_results_dict
results = load_results_from_path(results_path)

results_proposed_method = parse_results_dict(results['decision_tree-xgboost-dt-double'], 'double-GB')
results_proposed_method

c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Users\ericv\code\stacked-new\.venv\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

{'151': {'train':     hybrid_n_correct_total  hybrid_n_correct_easy  hybrid_n_correct_hard  \
  0                      137                     71                     66
  1                      124                     69                     55
  2                      111                     51                     60
  3                      131                     71                     60
  4                      125                     64                     61
  5                      127                     62                     65
  6                      116                     41                     75
  7                      111                     55                     56
  8                      101                     60                     41
  9                      116                     66                     50
  10                     113                     76                     37
  11                     111                     61                     50
  12                     107                     52                     55
  13                     115                     84                     31
  14                     148                     57                     91
  15                     131                     65                     66
  16                     121                     60                     61
  17                     133                     56                     77
  18                     114                     55                     59
  19                     125                     67                     58
  20                     119                     75                     44
  21                     117                     67                     50
  22                     125                     39                     86
  23                      99                     56                     43
  24                      95                     53                     42
  25                     118                     55                     63
  26                     120                     53                     67
  27                     107                     63                     44
  28                     127                     55                     72
  29                     125                     66                     59
  30                     122                     63                     59
  31                     116                     76                     40
  32                     122                     43                     79
  33                     123                     65                     58
  34                     117                     82                     35
  35                     124                     57                     67
  36                     129                     68                     61
  37                     121                     63                     58
  38                     115                     50                     65
  39                     123                     96                     27
  40                     120                    109                     11
  41                     120                     64                     56
  42                     118                     75                     43
  43                     108                     60                     48
  44                     124                     63                     61
  45                     112                     42                     70
  46                     126                     36                     90
  47                     117                     72                     45
  48                     115                     79                     36
  49                     119                     70                     49

      hybrid_n_reject  hybrid_accuracy_all  hybrid_accuracy_easy  \
  0                48             0.985612              0.972603
  1                62             0.992000              0.985714
  2                75             0.991071              0.980769
  3                54             0.984962              0.972603
  4                59             0.976562              0.955224
  5                59             0.992188              0.984127
  6                71             1.000000              1.000000
  7                75             0.991071              0.982143
  8                84             0.980583              0.967742
  9                69             0.983051              0.970588
  10               73             0.982609              0.974359
  11               74             0.973684              0.953125
  12               80             1.000000              1.000000
  13               71             0.991379              0.988235
  14               38             0.993289              0.982759
  15               56             1.000000              1.000000
  16               64             0.983740              0.967742
  17               53             0.992537              0.982456
  18               73             1.000000              1.000000
  19               61             0.992063              0.985294
  20               67             0.991667              0.986842
  21               70             0.991525              0.985294
  22               62             0.992063              0.975000
  23               85             0.970588              0.949153
  24               91             0.989583              0.981481
  25               68             0.991597              0.982143
  26               66             0.991736              0.981481
  27               78             0.981651              0.969231
  28               58             0.984496              0.964912
  29               61             0.992063              0.985075
  30               65             1.000000              1.000000
  31               70             0.991453              0.987013
  32               65             0.991870              0.977273
  33               63             0.984000              0.970149
  34               67             0.975000              0.964706
  35               63             1.000000              1.000000
  36               57             0.992308              0.985507
  37               66             1.000000              1.000000
  38               72             1.000000              1.000000
  39               62             0.984000              0.979592
  40               65             0.983607              0.981982
  41               66             0.991736              0.984615
  42               67             0.983333              0.974026
  43               77             0.972973              0.952381
  44               61             0.976378              0.954545
  45               74             0.991150              0.976744
  46               61             1.000000              1.000000
  47               67             0.975000              0.960000
  48               71             0.982906              0.975309
  49               68             0.991667              0.985915

      hybrid_accuracy_hard  glass_precision  glass_recall  glass_specificity  \
  0                    1.0         0.972854      0.973506           0.973506
  1                    1.0         0.951430      0.953506           0.953506
  2                    1.0         0.923598      0.916782           0.916782
  3                    1.0         0.968627      0.967011           0.967011
  4                    1.0         0.928662      0.929253           0.929253
  5                    1.0         0.956604      0.957759           0.957759
  6                    1.0         0.949918      0.944023           0.944023
  7                    1.0         0.928284      0.915287           0.915287
  8                    1.0         0.948274      0.944770           0.944770
  9                    1.0         0.952941      0.950758           0.950758
  10                   1.0         0.956444      0.949545           0.949545
  11                   1.0         0.947332      0.945909           0.945909
  12                   1.0         0.943612      0.939023           0.939023
  13                   1.0         0.959106      0.955517           0.955517
  14                   1.0         0.935655      0.937759           0.937759
  15                   1.0         0.909164      0.908506           0.908506
  16                   1.0         0.954472      0.949770           0.949770
  17                   1.0         0.962963      0.954023           0.954023
  18                   1.0         0.965331      0.960517           0.960517
  19                   1.0         0.932468      0.921034           0.921034
  20                   1.0         0.949710      0.944444           0.944444
  21                   1.0         0.931373      0.930000           0.930000
  22                   1.0         0.928454      0.916136           0.916136
  23                   1.0         0.930693      0.930000           0.930000
  24                   1.0         0.946264      0.946264           0.946264
  25                   1.0         0.960808      0.954770           0.954770
  26                   1.0         0.936275      0.934770           0.934770
  27                   1.0         0.940657      0.941264           0.941264
  28                   1.0         0.953017      0.950517           0.950517
  29                   1.0         0.939367      0.926034           0.926034
  30                   1.0         0.961913      0.963506           0.963506
  31                   1.0         0.952941      0.950758           0.950758
  32                   1.0         0.904255      0.905909           0.905909
  33                   1.0         0.948489      0.945227           0.945227
  34                   1.0         0.959106      0.955517           0.955517
  35                   1.0         0.920596      0.918276           0.918276
  36                   1.0         0.927361      0.908793           0.908793
  37                   1.0         0.972623      0.974253           0.974253
  38                   1.0         0.954545      0.942529           0.942529
  39                   1.0         0.967759      0.967759           0.967759
  40                   1.0         0.978044      0.979253           0.979253
  41                   1.0         0.952070      0.954253           0.954253
  42                   1.0         0.965130      0.960859           0.960859
  43                   1.0         0.946591      0.946591           0.946591
  44                   1.0         0.953227      0.950909           0.950909
  45                   1.0         0.928662      0.929253           0.929253
  46                   1.0         0.957843      0.956264           0.956264
  47                   1.0         0.921478      0.922348           0.922348
  48                   1.0         0.920600      0.922273           0.922273
  49                   1.0         0.930324      0.922500           0.922500

      ...  pct_easy_as_easy  pct_easy_as_hard  pct_easy_as_vhard  \
  0   ...          0.390110          0.362637           0.247253
  1   ...          0.387640          0.297753           0.314607
  2   ...          0.296512          0.331395           0.372093
  3   ...          0.392265          0.325967           0.281768
  4   ...          0.369942          0.312139           0.317919
  5   ...          0.346369          0.346369           0.307263
  6   ...          0.231638          0.412429           0.355932
  7   ...          0.319767          0.313953           0.366279
  8   ...          0.338983          0.231638           0.429379
  9   ...          0.370787          0.275281           0.353933
  10  ...          0.424581          0.201117           0.374302
  11  ...          0.342697          0.269663           0.387640
  12  ...          0.295455          0.312500           0.392045
  13  ...          0.469274          0.173184           0.357542
  14  ...          0.325714          0.474286           0.200000
  15  ...          0.384615          0.343195           0.272189
  16  ...          0.337079          0.337079           0.325843
  17  ...          0.312849          0.391061           0.296089
  18  ...          0.305556          0.322222           0.372222
  19  ...          0.387283          0.317919           0.294798
  20  ...          0.423729          0.248588           0.327684
  21  ...          0.385057          0.270115           0.344828
  22  ...          0.225434          0.485549           0.289017
  23  ...          0.323699          0.225434           0.450867
  24  ...          0.299435          0.231638           0.468927
  25  ...          0.307263          0.351955           0.340782
  26  ...          0.302857          0.360000           0.337143
  27  ...          0.357955          0.232955           0.409091
  28  ...          0.308989          0.404494           0.286517
  29  ...          0.379310          0.327586           0.293103
  30  ...          0.350000          0.316667           0.333333
  31  ...          0.426966          0.219101           0.353933
  32  ...          0.252941          0.405882           0.341176
  33  ...          0.365169          0.320225           0.314607
  34  ...          0.458101          0.195531           0.346369
  35  ...          0.331395          0.354651           0.313953
  36  ...          0.397661          0.333333           0.269006
  37  ...          0.346154          0.307692           0.346154
  38  ...          0.282486          0.350282           0.367232
  39  ...          0.530387          0.149171           0.320442
  40  ...          0.595628          0.060109           0.344262
  41  ...          0.359551          0.303371           0.337079
  42  ...          0.416667          0.227778           0.355556
  43  ...          0.337079          0.258427           0.404494
  44  ...          0.351955          0.335196           0.312849
  45  ...          0.242775          0.364162           0.393064
  46  ...          0.201117          0.491620           0.307263
  47  ...          0.418605          0.244186           0.337209
  48  ...          0.456647          0.184971           0.358382
  49  ...          0.402299          0.264368           0.333333

      pct_hard_as_easy  pct_hard_as_hard  pct_hard_as_vhard  pct_vhard_as_easy  \
  0           0.400000          0.000000           0.600000                NaN
  1           0.111111          0.222222           0.666667                NaN
  2           0.066667          0.200000           0.733333                NaN
  3           0.333333          0.166667           0.500000                NaN
  4           0.214286          0.500000           0.285714                NaN
  5           0.125000          0.375000           0.500000                NaN
  6           0.000000          0.200000           0.800000                NaN
  7           0.066667          0.133333           0.800000                NaN
  8           0.200000          0.000000           0.800000                NaN
  9           0.222222          0.111111           0.666667                NaN
  10          0.222222          0.111111           0.666667                NaN
  11          0.300000          0.200000           0.500000                NaN
  12          0.000000          0.000000           1.000000                NaN
  13          0.125000          0.000000           0.875000                NaN
  14          0.083333          0.666667           0.250000                NaN
  15          0.000000          0.444444           0.555556                NaN
  16          0.222222          0.111111           0.666667                NaN
  17          0.125000          0.875000           0.000000                NaN
  18          0.000000          0.142857           0.857143                NaN
  19          0.071429          0.214286           0.714286                NaN
  20          0.100000          0.000000           0.900000                NaN
  21          0.071429          0.214286           0.714286                NaN
  22          0.066667          0.133333           0.800000                NaN
  23          0.214286          0.285714           0.500000                NaN
  24          0.100000          0.100000           0.800000                NaN
  25          0.125000          0.000000           0.875000                NaN
  26          0.083333          0.333333           0.583333                NaN
  27          0.181818          0.272727           0.545455                NaN
  28          0.222222          0.000000           0.777778                NaN
  29          0.076923          0.153846           0.769231                NaN
  30          0.000000          0.285714           0.714286                NaN
  31          0.111111          0.111111           0.777778                NaN
  32          0.055556          0.555556           0.388889                NaN
  33          0.200000          0.100000           0.700000                NaN
  34          0.375000          0.000000           0.625000                NaN
  35          0.000000          0.400000           0.600000                NaN
  36          0.062500          0.250000           0.687500                NaN
  37          0.000000          0.400000           0.600000                NaN
  38          0.000000          0.300000           0.700000                NaN
  39          0.333333          0.000000           0.666667                NaN
  40          0.500000          0.000000           0.500000                NaN
  41          0.111111          0.222222           0.666667                NaN
  42          0.285714          0.285714           0.428571                NaN
  43          0.300000          0.200000           0.500000                NaN
  44          0.333333          0.111111           0.555556                NaN
  45          0.071429          0.500000           0.428571                NaN
  46          0.000000          0.250000           0.750000                NaN
  47          0.200000          0.200000           0.600000                NaN
  48          0.133333          0.266667           0.600000                NaN
  49          0.071429          0.214286           0.714286                NaN

      pct_vhard_as_hard  pct_vhard_as_vhard  grader_kappa
  0                 NaN                 NaN      0.013120
  1                 NaN                 NaN      0.036537
  2                 NaN                 NaN      0.047787
  3                 NaN                 NaN      0.011870
  4                 NaN                 NaN      0.011252
  5                 NaN                 NaN      0.021621
  6                 NaN                 NaN      0.036992
  7                 NaN                 NaN      0.056079
  8                 NaN                 NaN      0.026456
  9                 NaN                 NaN      0.024941
  10                NaN                 NaN      0.026456
  11                NaN                 NaN      0.008766
  12                NaN                 NaN      0.051859
  13                NaN                 NaN      0.042823
  14                NaN                 NaN      0.028115
  15                NaN                 NaN      0.079394
  16                NaN                 NaN      0.025365
  17                NaN                 NaN     -0.005892
  18                NaN                 NaN      0.031088
  19                NaN                 NaN      0.065900
  20                NaN                 NaN      0.055989
  21                NaN                 NaN      0.056072
  22                NaN                 NaN      0.058605
  23                NaN                 NaN      0.011249
  24                NaN                 NaN      0.025617

In [3]:
results_without_reject = parse_results_dict(results['decision_tree-xgboost-dt-binary'], 'binary')
results_without_reject

{'151': {'train':     hybrid_n_correct_total  hybrid_n_correct_easy  hybrid_n_correct_hard  \
  0                      185                     71                    114
  1                      186                     69                    117
  2                      186                     51                    135
  3                      185                     71                    114
  4                      184                     64                    120
  5                      186                     62                    124
  6                      187                     41                    146
  7                      186                     55                    131
  8                      185                     60                    125
  9                      185                     66                    119
  10                     186                     76                    110
  11                     185                     61                    124
  12                     187                     52                    135
  13                     186                     84                    102
  14                     186                     57                    129
  15                     187                     65                    122
  16                     185                     60                    125
  17                     186                     56                    130
  18                     187                     55                    132
  19                     186                     67                    119
  20                     186                     75                    111
  21                     187                     67                    120
  22                     187                     39                    148
  23                     184                     56                    128
  24                     186                     53                    133
  25                     186                     55                    131
  26                     186                     53                    133
  27                     185                     63                    122
  28                     185                     55                    130
  29                     186                     66                    120
  30                     187                     63                    124
  31                     186                     76                    110
  32                     187                     43                    144
  33                     186                     65                    121
  34                     184                     82                    102
  35                     187                     57                    130
  36                     186                     68                    118
  37                     187                     63                    124
  38                     187                     50                    137
  39                     185                     96                     89
  40                     185                    109                     76
  41                     186                     64                    122
  42                     185                     75                    110
  43                     185                     60                    125
  44                     185                     63                    122
  45                     186                     42                    144
  46                     187                     36                    151
  47                     184                     72                    112
  48                     186                     79                    107
  49                     187                     70                    117

      hybrid_n_reject  hybrid_accuracy_all  hybrid_accuracy_easy  \
  0                 0             0.989305              0.972603
  1                 0             0.994652              0.985714
  2                 0             0.994652              0.980769
  3                 0             0.989305              0.972603
  4                 0             0.983957              0.955224
  5                 0             0.994652              0.984127
  6                 0             1.000000              1.000000
  7                 0             0.994652              0.982143
  8                 0             0.989305              0.967742
  9                 0             0.989305              0.970588
  10                0             0.989362              0.974359
  11                0             0.984043              0.953125
  12                0             1.000000              1.000000
  13                0             0.994652              0.988235
  14                0             0.994652              0.982759
  15                0             1.000000              1.000000
  16                0             0.989305              0.967742
  17                0             0.994652              0.982456
  18                0             1.000000              1.000000
  19                0             0.994652              0.985294
  20                0             0.994652              0.986842
  21                0             0.994681              0.985294
  22                0             0.994681              0.975000
  23                0             0.983957              0.949153
  24                0             0.994652              0.981481
  25                0             0.994652              0.982143
  26                0             0.994652              0.981481
  27                0             0.989305              0.969231
  28                0             0.989305              0.964912
  29                0             0.994652              0.985075
  30                0             1.000000              1.000000
  31                0             0.994652              0.987013
  32                0             0.994681              0.977273
  33                0             0.989362              0.970149
  34                0             0.983957              0.964706
  35                0             1.000000              1.000000
  36                0             0.994652              0.985507
  37                0             1.000000              1.000000
  38                0             1.000000              1.000000
  39                0             0.989305              0.979592
  40                0             0.989305              0.981982
  41                0             0.994652              0.984615
  42                0             0.989305              0.974026
  43                0             0.984043              0.952381
  44                0             0.984043              0.954545
  45                0             0.994652              0.976744
  46                0             1.000000              1.000000
  47                0             0.983957              0.960000
  48                0             0.989362              0.975309
  49                0             0.994681              0.985915

      hybrid_accuracy_hard  glass_precision  glass_recall  glass_specificity  \
  0                    1.0         0.972854      0.973506           0.973506
  1                    1.0         0.951430      0.953506           0.953506
  2                    1.0         0.923598      0.916782           0.916782
  3                    1.0         0.968627      0.967011           0.967011
  4                    1.0         0.928662      0.929253           0.929253
  5                    1.0         0.956604      0.957759           0.957759
  6                    1.0         0.949918      0.944023           0.944023
  7                    1.0         0.928284      0.915287           0.915287
  8                    1.0         0.948274      0.944770           0.944770
  9                    1.0         0.952941      0.950758           0.950758
  10                   1.0         0.956444      0.949545           0.949545
  11                   1.0         0.947332      0.945909           0.945909
  12                   1.0         0.943612      0.939023           0.939023
  13                   1.0         0.959106      0.955517           0.955517
  14                   1.0         0.935655      0.937759           0.937759
  15                   1.0         0.909164      0.908506           0.908506
  16                   1.0         0.954472      0.949770           0.949770
  17                   1.0         0.962963      0.954023           0.954023
  18                   1.0         0.965331      0.960517           0.960517
  19                   1.0         0.932468      0.921034           0.921034
  20                   1.0         0.949710      0.944444           0.944444
  21                   1.0         0.931373      0.930000           0.930000
  22                   1.0         0.928454      0.916136           0.916136
  23                   1.0         0.930693      0.930000           0.930000
  24                   1.0         0.946264      0.946264           0.946264
  25                   1.0         0.960808      0.954770           0.954770
  26                   1.0         0.936275      0.934770           0.934770
  27                   1.0         0.940657      0.941264           0.941264
  28                   1.0         0.953017      0.950517           0.950517
  29                   1.0         0.939367      0.926034           0.926034
  30                   1.0         0.961913      0.963506           0.963506
  31                   1.0         0.952941      0.950758           0.950758
  32                   1.0         0.904255      0.905909           0.905909
  33                   1.0         0.948489      0.945227           0.945227
  34                   1.0         0.959106      0.955517           0.955517
  35                   1.0         0.920596      0.918276           0.918276
  36                   1.0         0.927361      0.908793           0.908793
  37                   1.0         0.972623      0.974253           0.974253
  38                   1.0         0.954545      0.942529           0.942529
  39                   1.0         0.967759      0.967759           0.967759
  40                   1.0         0.978044      0.979253           0.979253
  41                   1.0         0.952070      0.954253           0.954253
  42                   1.0         0.965130      0.960859           0.960859
  43                   1.0         0.946591      0.946591           0.946591
  44                   1.0         0.953227      0.950909           0.950909
  45                   1.0         0.928662      0.929253           0.929253
  46                   1.0         0.957843      0.956264           0.956264
  47                   1.0         0.921478      0.922348           0.922348
  48                   1.0         0.920600      0.922273           0.922273
  49                   1.0         0.930324      0.922500           0.922500

      ...  pct_easy_as_easy  pct_easy_as_hard  pct_easy_as_vhard  \
  0   ...          0.390110          0.609890                0.0
  1   ...          0.387640          0.612360                0.0
  2   ...          0.296512          0.703488                0.0
  3   ...          0.392265          0.607735                0.0
  4   ...          0.369942          0.630058                0.0
  5   ...          0.346369          0.653631                0.0
  6   ...          0.231638          0.768362                0.0
  7   ...          0.319767          0.680233                0.0
  8   ...          0.338983          0.661017                0.0
  9   ...          0.370787          0.629213                0.0
  10  ...          0.424581          0.575419                0.0
  11  ...          0.342697          0.657303                0.0
  12  ...          0.295455          0.704545                0.0
  13  ...          0.469274          0.530726                0.0
  14  ...          0.325714          0.674286                0.0
  15  ...          0.384615          0.615385                0.0
  16  ...          0.337079          0.662921                0.0
  17  ...          0.312849          0.687151                0.0
  18  ...          0.305556          0.694444                0.0
  19  ...          0.387283          0.612717                0.0
  20  ...          0.423729          0.576271                0.0
  21  ...          0.385057          0.614943                0.0
  22  ...          0.225434          0.774566                0.0
  23  ...          0.323699          0.676301                0.0
  24  ...          0.299435          0.700565                0.0
  25  ...          0.307263          0.692737                0.0
  26  ...          0.302857          0.697143                0.0
  27  ...          0.357955          0.642045                0.0
  28  ...          0.308989          0.691011                0.0
  29  ...          0.379310          0.620690                0.0
  30  ...          0.350000          0.650000                0.0
  31  ...          0.426966          0.573034                0.0
  32  ...          0.252941          0.747059                0.0
  33  ...          0.365169          0.634831                0.0
  34  ...          0.458101          0.541899                0.0
  35  ...          0.331395          0.668605                0.0
  36  ...          0.397661          0.602339                0.0
  37  ...          0.346154          0.653846                0.0
  38  ...          0.282486          0.717514                0.0
  39  ...          0.530387          0.469613                0.0
  40  ...          0.595628          0.404372                0.0
  41  ...          0.359551          0.640449                0.0
  42  ...          0.416667          0.583333                0.0
  43  ...          0.337079          0.662921                0.0
  44  ...          0.351955          0.648045                0.0
  45  ...          0.242775          0.757225                0.0
  46  ...          0.201117          0.798883                0.0
  47  ...          0.418605          0.581395                0.0
  48  ...          0.456647          0.543353                0.0
  49  ...          0.402299          0.597701                0.0

      pct_hard_as_easy  pct_hard_as_hard  pct_hard_as_vhard  pct_vhard_as_easy  \
  0           0.400000          0.600000                0.0                NaN
  1           0.111111          0.888889                0.0                NaN
  2           0.066667          0.933333                0.0                NaN
  3           0.333333          0.666667                0.0                NaN
  4           0.214286          0.785714                0.0                NaN
  5           0.125000          0.875000                0.0                NaN
  6           0.000000          1.000000                0.0                NaN
  7           0.066667          0.933333                0.0                NaN
  8           0.200000          0.800000                0.0                NaN
  9           0.222222          0.777778                0.0                NaN
  10          0.222222          0.777778                0.0                NaN
  11          0.300000          0.700000                0.0                NaN
  12          0.000000          1.000000                0.0                NaN
  13          0.125000          0.875000                0.0                NaN
  14          0.083333          0.916667                0.0                NaN
  15          0.000000          1.000000                0.0                NaN
  16          0.222222          0.777778                0.0                NaN
  17          0.125000          0.875000                0.0                NaN
  18          0.000000          1.000000                0.0                NaN
  19          0.071429          0.928571                0.0                NaN
  20          0.100000          0.900000                0.0                NaN
  21          0.071429          0.928571                0.0                NaN
  22          0.066667          0.933333                0.0                NaN
  23          0.214286          0.785714                0.0                NaN
  24          0.100000          0.900000                0.0                NaN
  25          0.125000          0.875000                0.0                NaN
  26          0.083333          0.916667                0.0                NaN
  27          0.181818          0.818182                0.0                NaN
  28          0.222222          0.777778                0.0                NaN
  29          0.076923          0.923077                0.0                NaN
  30          0.000000          1.000000                0.0                NaN
  31          0.111111          0.888889                0.0                NaN
  32          0.055556          0.944444                0.0                NaN
  33          0.200000          0.800000                0.0                NaN
  34          0.375000          0.625000                0.0                NaN
  35          0.000000          1.000000                0.0                NaN
  36          0.062500          0.937500                0.0                NaN
  37          0.000000          1.000000                0.0                NaN
  38          0.000000          1.000000                0.0                NaN
  39          0.333333          0.666667                0.0                NaN
  40          0.500000          0.500000                0.0                NaN
  41          0.111111          0.888889                0.0                NaN
  42          0.285714          0.714286                0.0                NaN
  43          0.300000          0.700000                0.0                NaN
  44          0.333333          0.666667                0.0                NaN
  45          0.071429          0.928571                0.0                NaN
  46          0.000000          1.000000                0.0                NaN
  47          0.200000          0.800000                0.0                NaN
  48          0.133333          0.866667                0.0                NaN
  49          0.071429          0.928571                0.0                NaN

      pct_vhard_as_hard  pct_vhard_as_vhard  grader_kappa
  0                 NaN                 NaN     -0.000853
  1                 NaN                 NaN      0.041294
  2                 NaN                 NaN      0.049417
  3                 NaN                 NaN      0.006074
  4                 NaN                 NaN      0.034750
  5                 NaN                 NaN      0.027930
  6                 NaN                 NaN      0.031236
  7                 NaN                 NaN      0.055879
  8                 NaN                 NaN      0.021631
  9                 NaN                 NaN      0.021841
  10                NaN                 NaN      0.031973
  11                NaN                 NaN      0.006692
  12                NaN                 NaN      0.047016
  13                NaN                 NaN      0.052065
  14                NaN                 NaN      0.043745
  15                NaN                 NaN      0.107399
  16                NaN                 NaN      0.016135
  17                NaN                 NaN      0.022676
  18                NaN                 NaN      0.031891
  19                NaN                 NaN      0.071034
  20                NaN                 NaN      0.056157
  21                NaN                 NaN      0.069989
  22                NaN                 NaN      0.031446
  23                NaN                 NaN      0.023074
  24                NaN                 NaN      0.029318

In [12]:
import pandas as pd
from pathlib import Path

# Update this to the folder containing your 50 text files
data_dir = results_path / '891'

dfs = []
for i in range(50):
    file_path = data_dir / f"{i}-decision_tree-xgboost-dt-test-double.txt"
    if file_path.exists():
        dfs.append(pd.read_csv(file_path))
    else:
        print(f"Warning: File not found: {file_path.name}")

if dfs:
    # Combine all 50 runs into one DataFrame
    df = pd.concat(dfs, ignore_index=True)

    # A pattern is rejected if both graders equal 1
    df['rejected'] = (df['y_grader'] == 1) & (df['y_grader2'] == 1)

    # Group by the true class to see rejection stats
    rejection_stats = df.groupby('y_truth').agg(
        total_patterns=('rejected', 'count'),
        rejected_count=('rejected', 'sum')
    )
    
    # Calculate the percentage
    rejection_stats['rejection_rate (%)'] = (
        rejection_stats['rejected_count'] / rejection_stats['total_patterns'] * 100
    ).round(2)

    display(rejection_stats)
else:
    print("No files were loaded. Please check your data_dir path.")

         total_patterns  rejected_count  rejection_rate (%)
y_truth
0               1091670          262137               24.01
1                176730          120300               68.07

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

# Update this to the folder containing your 50 text files
data_dir = results_path / '572'

dfs = []
for i in range(50):
    file_path = data_dir / f"{i}-decision_tree-xgboost-dt-test-double.txt"
    if file_path.exists():
        dfs.append(pd.read_csv(file_path))

if dfs:
    df = pd.concat(dfs, ignore_index=True)
    
    # 1. Define predictions without reject (GB-Grader priority)
    df['y_pred_no_reject'] = np.where(df['y_grader'] == 0, df['y_glass'], df['y_black'])
    
    # 2. Define rejection mask (Both Graders = 1)
    df['rejected'] = (df['y_grader'] == 1) & (df['y_grader2'] == 1)
    
    results = []
    classes = sorted(df['y_truth'].unique())
    
    for c in classes:
        # --- NO REJECT METRICS ---
        tp_nr = len(df[(df['y_truth'] == c) & (df['y_pred_no_reject'] == c)])
        fp_nr = len(df[(df['y_truth'] != c) & (df['y_pred_no_reject'] == c)])
        fn_nr = len(df[(df['y_truth'] == c) & (df['y_pred_no_reject'] != c)])
        tn_nr = len(df[(df['y_truth'] != c) & (df['y_pred_no_reject'] != c)])
        
        prec_nr = tp_nr / (tp_nr + fp_nr) if (tp_nr + fp_nr) > 0 else 0.0
        rec_nr = tp_nr / (tp_nr + fn_nr) if (tp_nr + fn_nr) > 0 else 0.0
        spec_nr = tn_nr / (tn_nr + fp_nr) if (tn_nr + fp_nr) > 0 else 0.0
        
        # --- WITH REJECT METRICS ---
        # Filter to only the patterns the framework accepted
        df_acc = df[~df['rejected']]
        tp_wr = len(df_acc[(df_acc['y_truth'] == c) & (df_acc['y_pred_no_reject'] == c)])
        fp_wr = len(df_acc[(df_acc['y_truth'] != c) & (df_acc['y_pred_no_reject'] == c)])
        fn_wr = len(df_acc[(df_acc['y_truth'] == c) & (df_acc['y_pred_no_reject'] != c)])
        tn_wr = len(df_acc[(df_acc['y_truth'] != c) & (df_acc['y_pred_no_reject'] != c)])
        
        prec_wr = tp_wr / (tp_wr + fp_wr) if (tp_wr + fp_wr) > 0 else 0.0
        rec_wr = tp_wr / (tp_wr + fn_wr) if (tp_wr + fn_wr) > 0 else 0.0
        spec_wr = tn_wr / (tn_wr + fp_wr) if (tn_wr + fp_wr) > 0 else 0.0
        
        # Contextual Stats
        total_c = len(df[df['y_truth'] == c])
        rej_c = len(df[(df['y_truth'] == c) & df['rejected']])
        rej_rate = rej_c / total_c * 100 if total_c > 0 else 0.0
        
        results.append({
            'Class': c,
            'Total Patterns': total_c,
            'Rejected': rej_c,
            'Reject Rate (%)': round(rej_rate, 2),
            'Prec (No Rej)': round(prec_nr * 100, 2),
            'Prec (Reject)': round(prec_wr * 100, 2),
            'Rec (No Rej)': round(rec_nr * 100, 2),
            'Rec (Reject)': round(rec_wr * 100, 2),
            'Spec (No Rej)': round(spec_nr * 100, 2),
            'Spec (Reject)': round(spec_wr * 100, 2),
            'Accepted TP': tp_wr,
            'Accepted FP': fp_wr,
            'Accepted FN': fn_wr
        })
        
    res_df = pd.DataFrame(results)
    display(res_df)
else:
    print("No files were loaded. Please check your data_dir path.")

,Class,Total Patterns,Rejected,Reject Rate (%),Prec (No Rej),Prec (Reject),Rec (No Rej),Rec (Reject),Spec (No Rej),Spec (Reject),Accepted TP,Accepted FP,Accepted FN
0,0,32995,2238,6.78,97.63,98.96,99.42,99.96,27.73,1.23,30744,322,13
1,1,1100,774,70.36,61.24,23.53,27.73,1.23,99.42,99.96,4,13,322

In [7]:
import pandas as pd
from pathlib import Path

# Update this to the folder containing the Taiwanese Bankruptcy results
data_dir = results_path / '43'

partitions_with_zero_accepted = 0
total_partitions = 0
class_to_check = 1  # 1 is the minority class for bankruptcy

for i in range(50):
    file_path = data_dir / f"{i}-decision_tree-xgboost-dt-test-double.txt"
    
    if file_path.exists():
        total_partitions += 1
        df = pd.read_csv(file_path)
        
        # A pattern is rejected if both graders equal 1
        rejected_mask = (df['y_grader'] == 1) & (df['y_grader2'] == 1)
        
        # Filter to only the ACCEPTED patterns
        df_accepted = df[~rejected_mask]
        
        # Count how many accepted patterns belong to Class 1
        accepted_class_count = len(df_accepted[df_accepted['y_truth'] == class_to_check])
        
        # If the reject option wiped out the entire class for this fold
        if accepted_class_count == 0:
            partitions_with_zero_accepted += 1

if total_partitions > 0:
    print(f"Total partitions analyzed: {total_partitions}")
    print(f"Partitions with ZERO accepted patterns for Class {class_to_check}: {partitions_with_zero_accepted}")
else:
    print("No files were loaded. Please check your data_dir path.")

Total partitions analyzed: 50
Partitions with ZERO accepted patterns for Class 1: 0

In [8]:
import pandas as pd
import numpy as np
from pathlib import Path

# Update this to the folder containing the Taiwanese Bankruptcy results
data_dir = results_path / '572'

partitions_with_zero_predictions = 0
total_partitions = 0
class_to_check = 1  # 1 is the minority class for bankruptcy

# Assuming standard DIFFICULTY mapping from earlier
DIFFICULTY_EASY = 0
DIFFICULTY_HARD = 1
DIFFICULTY_VERY_HARD = 2

for i in range(50):
    file_path = data_dir / f"{i}-decision_tree-xgboost-dt-test-double.txt"
    
    if file_path.exists():
        total_partitions += 1
        df = pd.read_csv(file_path)
        
        # Determine predictions without reject
        df['y_pred_no_reject'] = np.where(df['y_grader'] == 0, df['y_glass'], df['y_black'])
        
        # A pattern is rejected if both graders equal 1
        rejected_mask = (df['y_grader'] == 1) & (df['y_grader2'] == 1)
        
        # Filter to only the ACCEPTED patterns
        df_accepted = df[~rejected_mask]
        
        # Count how many times the model PREDICTED Class 1 in the accepted pool
        accepted_predictions_count = len(df_accepted[df_accepted['y_pred_no_reject'] == class_to_check])
        
        # If the model made ZERO predictions for Class 1 in this fold
        if accepted_predictions_count == 0:
            partitions_with_zero_predictions += 1

if total_partitions > 0:
    print(f"Total partitions analyzed: {total_partitions}")
    print(f"Partitions with ZERO Class {class_to_check} PREDICTIONS: {partitions_with_zero_predictions}")
else:
    print("No files were loaded. Please check your data_dir path.")

Total partitions analyzed: 50
Partitions with ZERO Class 1 PREDICTIONS: 35